<?php

return [
    'auth' => [
        'auth read',
    ],
    'manage' => [
        'all manage',
    ],
    'users' => [
        'users read',
        'users list',
        'users create',
        'users edit',
        'users delete',
    ],
    'profile' => [
        'profile read',
        'profile edit',
    ],
    'roles' => [
        'roles read',
        'roles list',
        'roles create',
        'roles edit',
        'roles delete',
    ],
    'permission' => [
        'permission read',
        'permission list',
        'permission create',
        'permission edit',
        'permission delete',
    ],
    'catalog' => [
        'products list',
        'products read',
        'products create',
        'products edit',
        'products delete',
        'size charts list',
        'size charts read',
        'size charts create',
        'size charts edit',
        'size charts delete',
        'products variants list',
        'products variants read',
        'products variants create',
        'products variants edit',
        'products variants delete',
        'products personalization list',
        'products personalization read',
        'products personalization create',
        'products personalization edit',
        'products personalization delete',
        'attributes list',
        'attributes create',
        'attributes edit',
        'attributes delete',
        'attributes values create',
        'attributes values edit',
        'attributes values delete',
    ],
    'marketing' => [
        'banners list',
        'banners read',
        'banners create',
        'banners edit',
        'banners delete',
        'promotions list',
        'promotions read',
        'promotions create',
        'promotions edit',
        'promotions delete',
    ],
    'commerce' => [
        'orders list',
        'orders read',
        'orders update',
    ],
    'dashboard' => [
        'dashboard read',
    ],
    'product_reviews' => [
        'product reviews list',
        'product reviews moderate',
    ],
    'tracking' => [
        'analytics events list',
        'analytics events read',
        'audit logs list',
        'audit logs read',
        'webhook inbox list',
        'webhook inbox read',
        'order status transitions list',
        'order status transitions read',
    ],
];
